---
title: "About me"
description: |
  I have been doing data science since long before data science was a thing. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



I have applied data science to telecom while at Alcatel/[Nokia](https://www.nokia.com/), [BlackBerry](https://www.blackberry.com), [Akamai](https://www.akamai.com/); fintech while at  [Ario/Thinking Capital](https://www.thinkingcapital.ca/); and eCommerce while at [Shopify](https://www.shopify.ca/). Most recently, I worked at [Meta](www.meta.com), on improving video recommendations.

I also teach an intro to data science course to MBA students at [University of Ottawa](https://telfer.uottawa.ca).  

I used to co-lead [Data for Good in Ottawa](https://ottawa.dataforgood.ca/): volunteer data scientists trying to make Ottawa better by helping local charities. You can see a bit more about how D4G Ottawa used to work, and largely still does, [here](https://datascienceottawa.wordpress.com/data-for-good-ottawa-intro-faq-status/). It is a great way to improve your data science skills, meet cool people, and help the city.

Before Alcatel, in reverse chronological order: I worked at a networking start-up (Sedona networks); managed the IT dept for the Liberal Party of Canada; did IT consulting for ISA Corporation; developed software for gas turbine engine test cells at MDS Aero Support; and worked at Lafarge, first as a strategic planning analyst, and later also doing IT support & some coding.

I have a PhD in Probability and Statistics, my thesis was an abstract version of figuring out how big a reordering buffer was needed on a router - which lead to figuring out some properties of random Mallows permutations. A not-so-technical overview of part of it is [here](https://github.com/prabinov42/MiscData/blob/master/ThesisSummary1.pdf).

My M.Sc. was about how to statistically estimate the effective bandwidth (which is a measure of resource usage) of various telecom network traffic streams.

You can find me on [LinkedIn](https://www.linkedin.com/in/peter-rabinovitch/),  [Twitter](https://twitter.com/prabinov42), and/or [Mastodon](https://mastodon.social/@prabinov42).  

