---
title: "The Full-Stat Data Scientist"
description: |
  What is a full-stat data scientist?
date: 2022-10-16
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I have been thinking about different data scientists, and I think we need a new term for some: the __full-stat__ data scientist. 

No, that is not a typo. Doubtless you have seen much about _full-stack_ data scientists - here we compare and contrast.

## What is a _full-stack_ data scientist?

A full-stack data scientist is one who can code, do stats, define metrics, etc. and take an idea from concept through pipeline to database design to building a dashboard. 

They have all of the basic skills of a regular data scientist with the added features of strong data engineering and software engineering skills. 

They are called _full-stack_ because they work with the full stack of data science tools. 

Full-stack data scientists own the data science product, from beginning to end. 

They frequently come with computer science degrees, and have taken a few stats courses, 

They will use words like _kubernetes_, _presto_, _spark_, _python_, _sql_, _pandas_, _pymc_, _scikit-learn_, and _kafka_.


## What is a _full-stat_ data scientist?

A _full-stat_ data scientist is a data scientist who can do much of what a full-stack data scientist can, and may be less skilled in the data engineering realm, but more skilled in statistics and quantitative modeling. 

Many come with advanced degrees in statistics, probability, and econometrics. 

They model the business situation using whatever techniques are required: analysis, stochastic modeling, simulation, optimization, game theory, etc. and determine which statistical techniques are required in order to analyze the data based on the model. 

They can adapt the techniques to the problem when needed or develop completely novel approaches when needed. They can evaluate trade-offs between inferential accuracy and run-time requirements of estimation algorithms. 

They are deeply skeptical about data and find anomalies that no one else does and figure out what to do about them. They care deeply about quantifying uncertainty and the impact of this uncertainty on business decisions.

They will use words like _R_, _Markov chain_, _glm_, _DAG_, and _Stan_. 


## Discussion

Both can be incredibly valuable to your organization. Full-stack data scientists are able to get the data from your customer facing systems into data sets suitable for analysis, create dash boards showing changes in metrics, and run A/B experiments. Full-stat data scientists can probe the deepest recesses of these data sets, and rigorously analyze them in ways that yield new insights.

Note that this does not mean a full-stat data scientist will not know sql, nor that a full-stack can't do a Bayesian analysis - just that their expertise, experience and mindset is generally in their own camp.


